# Site Settings
locale          : "en-US"
title           : "TERA Proxy"
title_separator : "-"
name            : "Risenio"
description     : "Simple, easy, modular event handling through a TERA proxy server."
url             : "https://zosz.github.io"
baseurl         : "/_"
repository      : "zosz/_"
teaser          : # path of fallback teaser image, e.g. "/assets/images/500x300.png"

# Social Sharing
og_image        : "/assets/images/site-icon.png"

# Site Author
author:
  name          : "Mie"
  avatar        : "https://avatars.githubusercontent.com/Risenio"
  bio           : "A someone who is trying to help.This is a updated fork of meishu's page."
  location      : "No where, really."
  email         :
  uri           :
  github        :
  tumblr        :
  youtube       :

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Gemfile
  - LICENSE
  
# Sass/SCSS
sass:
  style: compressed

# Outputting
timezone: America/Los_Angeles

# Plugins
gems: &gems
  - jekyll-avatar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# mimic GitHub Pages with --safe
whitelist: *gems

# Collections
collections:
  errors:
    output: true

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  # _errors
  - scope:
      path: ""
      type: errors
    values:
      layout: version
      sidebar:
        nav: "errors"